enum RootTemplate {
    static func files(for ctx: ProjectContext) -> [ScaffoldFile] {
        [
            ScaffoldFile(path: "Package.swift", content: packageSwift(ctx)),
            ScaffoldFile(path: ".gitignore", content: gitignore),
            ScaffoldFile(path: "README.md", content: readme(ctx)),
        ]
    }

    private static func packageSwift(_ ctx: ProjectContext) -> String {
        """
        // swift-tools-version: 6.0
        import PackageDescription

        let package = Package(
            name: "\(ctx.projectName)",
            platforms: [
                .macOS(.v15),
            ],
            dependencies: [
                \(ctx.kitDependencyLine)
            ],
            targets: [
                .target(
                    name: "\(ctx.aggregateTarget)",
                    dependencies: [
                        .product(name: "DDDKit", package: "swift-ddd-kit"),
                    ],
                    path: "Sources/\(ctx.aggregateTarget)",
                    resources: [
                        .process("event.yaml"),
                        .process("event-generator-config.yaml"),
                        .process("projection-model.yaml"),
                    ],
                    plugins: [
                        .plugin(name: "DomainEventGeneratorPlugin", package: "swift-ddd-kit"),
                        .plugin(name: "ModelGeneratorPlugin", package: "swift-ddd-kit"),
                    ]
                ),
                .executableTarget(
                    name: "\(ctx.appTarget)",
                    dependencies: [
                        "\(ctx.aggregateTarget)",
                        .product(name: "DDDKit", package: "swift-ddd-kit"),
                    ],
                    path: "Sources/\(ctx.appTarget)"
                ),
                .testTarget(
                    name: "\(ctx.testsTarget)",
                    dependencies: [
                        "\(ctx.aggregateTarget)",
                    ],
                    path: "Tests/\(ctx.testsTarget)"
                ),
            ]
        )
        """
    }

    private static let gitignore = """
        .DS_Store
        /.build
        /Packages
        xcuserdata/
        DerivedData/
        .swiftpm/configuration/registries.json
        .swiftpm/xcode/package.xcworkspace/contents.xcworkspacedata
        .netrc
        """

    private static func readme(_ ctx: ProjectContext) -> String {
        """
        # \(ctx.projectName)

        A [swift-ddd-kit](https://github.com/gradyzhuo/swift-ddd-kit) starter project,
        generated by `pangu project create`.

        ## Structure

        ```
        Sources/
          \(ctx.aggregateTarget)/            — the \(ctx.aggregateName) aggregate (write model)
            event.yaml                  — domain event schema (source of truth)
            event-generator-config.yaml — codegen access level / dependencies
            projection-model.yaml       — read model -> event wiring
            Entity/                     — \(ctx.aggregateName) aggregate root + commands
            Usecase/
              Port/In/                  — Input/Output/Usecase protocol per use case
              Port/Out/                 — \(ctx.aggregateName)Repository (write-side port)
              Service/                  — concrete Usecase implementations (DI target)
              Projector/                — \(ctx.aggregateName)Summary read model + projector
          \(ctx.appTarget)/                 — runnable demo wiring everything to KurrentDB
        Tests/
          \(ctx.testsTarget)/               — aggregate behavior tests (no I/O, no KurrentDB needed)
        ```

        Build-time plugins read `event.yaml` / `projection-model.yaml` and generate,
        under the hood:

        - `\(ctx.aggregateTarget)Protocol` — the aggregate root protocol (`Entity/\(ctx.aggregateName).swift` conforms to it)
        - `\(ctx.createdEvent)`, `\(ctx.renamedEvent)`, `\(ctx.deletedEvent)` — the domain event structs
        - `\(ctx.aggregateName)SummaryProjectorProtocol` — the read-side projector protocol
        - `\(ctx.aggregateTarget)EventMapper` — deserializes KurrentDB records back into typed events

        You will not find those types checked in anywhere — they live in
        `.build/plugins/outputs/.../generated/` and are rebuilt on every `swift build`.

        ## Prerequisites

        The demo app and any future integration tests talk to a real KurrentDB. Start
        one locally with Docker:

        ```bash
        docker run --rm -d -p 2113:2113 \\
          -e KURRENTDB_CLUSTER_SIZE=1 \\
          -e KURRENTDB_RUN_PROJECTIONS=All \\
          -e KURRENTDB_START_STANDARD_PROJECTIONS=true \\
          -e KURRENTDB_INSECURE=true \\
          -e KURRENTDB_ENABLE_ATOM_PUB_OVER_HTTP=true \\
          docker.kurrent.io/kurrent-latest/kurrentdb:latest
        ```

        `\(ctx.appTarget)` reads its connection string from the required
        `KURRENT_DB_URL` environment variable, e.g.:

        ```bash
        export KURRENT_DB_URL="kurrent://admin:changeit@localhost:2113?tls=false"
        ```

        ## Commands

        ```bash
        swift build                 # build (also runs the codegen plugins)
        swift run \(ctx.appTarget)   # create -> rename -> project -> delete a \(ctx.aggregateName), against KurrentDB
        swift test                  # aggregate-only unit tests, no KurrentDB required
        ```

        ## Extending this project

        1. Add a new event to `Sources/\(ctx.aggregateTarget)/event.yaml`.
        2. Add a `when(event:)` handler on `\(ctx.aggregateName)` (see `Entity/Commands/` for examples).
        3. Add an `Input` / `Output` / `Usecase` protocol under `Usecase/Port/In/<Name>/`
           and a concrete `Service` under `Usecase/Service/`, following the existing
           `Rename\(ctx.aggregateName)` use case as a template.
        4. If the new event should show up on the read side, list it under the
           relevant model in `projection-model.yaml` and handle it in
           `\(ctx.aggregateName)SummaryProjector`.

        For a production-shaped reference (multiple aggregates, HTTP API via
        Hummingbird, OpenAPI-generated adapters, cross-aggregate listeners), see the
        [swift-ddd-kit README](https://github.com/gradyzhuo/swift-ddd-kit) and its
        `samples/` directory.
        """
    }
}
